export "main"
fn fae_main(argc: i32, argv: &&u8): i32 {
	fae::intrinsics::user_main_function()
	return 0
}

#lang "slice_bound_check_failure"
fn slice_bound_check_failure(length: isize, index: isize) {
	let stderr = fae::libc::StdErrFile.*

	fae::libc::fprintf(
		stderr
		"Panic: Index %ld is out of range of slice with length %ld\n".pointer
		index
		length
	)
	fae::libc::fflush(stderr)

	fae::libc::exit(-1)
}
